version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https software-properties-common

      - run:
          name: Install librdkafka-dev
          command: |
            wget -qO - https://packages.confluent.io/deb/5.3/archive.key | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] http://security.debian.org/debian-security jessie/updates main"
            sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main"
            sudo apt-get update
            sudo apt-get install -y librdkafka-dev

      - run:
          name: Test
          command: |
            go get github.com/jstemmer/go-junit-report
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v . -coverprofile=${TEST_RESULTS}/coverage.out | tee ${TEST_RESULTS}/go-test.out

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run:
          name: Coverage
          command: go tool cover -html=${TEST_RESULTS}/coverage.out -o=${TEST_RESULTS}/coverage.html

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
